//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSWP {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox user;
		
		protected System.Web.UI.WebControls.TextBox numOfPlayers;
		
		protected System.Web.UI.WebControls.TextBox minTTPlay;
		
		protected System.Web.UI.WebControls.TextBox maxTTPlay;
		
		protected System.Web.UI.WebControls.TextBox minUserRating;
		
		protected System.Web.UI.WebControls.TextBox minBggRating;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
		
		protected System.Web.UI.WebControls.Label msg;
		
		protected System.Web.UI.WebControls.Table games;
	}
}
